### ISSUE TITLE
Renovate Bot

### ISSUE THREAD

**Issue by felipecrs** [denoland/nodetodenochallenge#24]
Project URL: https://github.com/renovatebot/renovate

I self-host Renovate Bot for my own usage, and I took this opportunity to try running it with Deno.

Fun fact: `deno cache` took 3.3 minutes to download its dependencies for the first time (without a lockfile), while `pnpm install` (without a lockfile) took 25s. With a lockfile, `pnpm install` takes 6s.

First try:

```console
❯ deno cache --lock-write lib/renovate.ts
error: Is a directory (os error 21)
    at file:///home/felipecrs/repos/renovate/lib/renovate.ts:4:59
```

Second try, now with `--unstable-sloppy-imports`:

```console
❯ deno cache --lock-write --unstable-sloppy-imports lib/renovate.ts
error: Relative import path "." not prefixed with / or ./ or ../
    at file:///home/felipecrs/repos/renovate/lib/util/cache/package/decorator.ts:7:31
```

And I believe this is a **compatibility issue** that deno can improve on.

Third try, changing all lines of code from `from '.';` to `from './index';` (there were 284 occurrences).

```console
❯ deno cache --lock-write --unstable-sloppy-imports lib/renovate.ts
error: Relative import path "stream/promises" not prefixed with / or ./ or ../
If you want to use a built-in Node module, add a "node:" prefix (ex. "node:stream/promises").
    at file:///home/felipecrs/repos/renovate/lib/util/hash.ts:2:26
```

4th try `--unstable-bare-node-builtins`:

```console
❯ deno cache --lock-write --unstable-sloppy-imports --unstable-bare-node-builtins lib/renovate.ts
error: Is a directory (os error 21)
    at file:///home/felipecrs/repos/renovate/lib/modules/manager/gradle/index.ts:5:40
```

Ok, this is another situation where deno can improve on the compatibility. It looks like there is both a file named `export.ts` and a folder `export` (with no `index.ts` inside), and the import line being `from './export';`. Apparently Node handles it by importing from the file, but Deno gets confused.

5th try, by adding `.ts` to `from './export'` (I actually had around 120 places to fix this, where some were indeed supposed to import from directories).

```console
❯ deno cache --lock-write --unstable-sloppy-imports --unstable-bare-node-builtins lib/renovate.ts
<no output>
```

Apparently, it worked, or at least I did not have any new errors. Unfortunately though, `deno.lock` didn't appear as I was expecting. Tried to run again, no luck still. Anyway, let's try running now:

```console
❯ deno run --unstable-sloppy-imports --unstable-bare-node-builtins lib/renovate.ts
error: Unable to load /home/felipecrs/repos/renovate/node_modules/.deno/source-map-support@0.5.21/node_modules/source-map-support/register imported from file:///home/felipecrs/repos/renovate/lib/renovate.ts

Caused by:
    No such file or directory (os error 2)
```

Honestly I don't know what that is. But now I will try with `pnpm install` and `--unstable-byonm`:

```console
❯ deno run --unstable-sloppy-imports --unstable-bare-node-builtins --unstable-byonm lib/renovate.ts
error: [ERR_MODULE_NOT_FOUND] Cannot find module "file:///home/felipecrs/repos/renovate/node_modules/.pnpm/source-map-support@0.5.21/node_modules/source-map-support/register" imported from "file:///home/felipecrs/repos/renovate/lib/renovate.ts"
    at file:///home/felipecrs/repos/renovate/lib/renovate.ts:3:8
```

Which was a similar error as before. I then changed `import 'source-map-support/register';` to `import 'source-map-support/register.js'`, which apparently fixed it.

```console
❯ deno run --unstable-sloppy-imports --unstable-bare-node-builtins --unstable-byonm lib/renovate.ts
error: Uncaught SyntaxError: The requested module '../expose.cjs' does not provide an export named 'pkg'
import { pkg } from '../expose.cjs';
         ^
    at <anonymous> (file:///home/felipecrs/repos/renovate/lib/instrumentation/index.ts:27:10)
```

This time I stopped using `--unstable-byonm` again, and I believe I fixed the error above by changing `module.exports =` to `exports ` in `expose.cjs`. Again, probably something that Deno can improve on.

```console
> deno run --unstable-sloppy-imports --unstable-bare-node-builtins lib/renovate.ts
error: Uncaught SyntaxError: The requested module 'upath' does not provide an export named 'dirname'
import { dirname } from 'upath';
         ^
    at <anonymous> (file:///home/felipecrs/repos/renovate/lib/modules/manager/bazel-module/extract.ts:1:10)
```

Ok, for now I have given up. If you have ideas to fix the problem above please let me know. Maybe I will continue tomorrow.

EDIT: let's continue.

I "fixed" this by replacing all `from 'upath';` to `from 'node:path';`, just to get it going.

```console
> deno run --unstable-sloppy-imports --unstable-bare-node-builtins lib/renovate.ts
error: Uncaught SyntaxError: The requested module 'azure-devops-node-api/interfaces/GitInterfaces.js' does not provide an export named 'PullRequestStatus'
  PullRequestStatus,
  ^
    at <anonymous> (file:///home/felipecrs/repos/renovate/lib/modules/platform/azure/util.ts:5:3)
```

And apparently the same issue happened but for another library. Unfortunately, this time I don't know how to workaround it. I suppose Deno's CommonJS compatibility layer is still a bit limited.

**Comment by felipecrs** [comment]
Fun fact, I ended up with 458 files changed in my `git status`.

**Comment by lambtron** [comment]
Appreciate your thorough log of your attempt here. Thank you!
