### ISSUE TITLE
`guardian/dotcom-rendering` fails to access `process.env`

### ISSUE THREAD

**Issue by mxdvl** [denoland/nodetodenochallenge#35]
Running the `server.js` output from the Webpack build of [`guardian/dotcom-rendering`](https://github.com/guardian/dotcom-rendering/tree/mxdvl/deno-challenge/dotcom-rendering) with 48 kLoC.

- checkout `mxdvl/deno-challenge` branch
- `cd dotcom-rendering`
- `make build`
- `deno run -A --unstable-sloppy-imports --unstable-bare-node-builtins dist/server.js`

Failure with output:

```sh
Warning Sloppy imports are not recommended and have a negative impact on performance.
Warning: Resolving "module" as "node:module" at file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:1:67. If you want to use a built-in Node module, add a "node:" prefix.
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'host')
    at isGuardianDomain (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:28313:1534)
    at Object.95066 (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:28313:1733)
    at __webpack_require__ (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:47938:41)
    at Module.75452 (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:11048:95)
    at __webpack_require__ (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:47938:41)
    at Object.74212 (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:15661:38)
    at __webpack_require__ (file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:47938:41)
    at file:///Users/max_duval/Code/dotcom-rendering/dotcom-rendering/dist/server.js:48119:36
```

**Comment by mxdvl** [comment]
Tried this again today, the error is slighly different… we got further down the file:

```sh
$ deno run -A --unstable-sloppy-imports --unstable-bare-node-builtins dist/server.js

Warning Sloppy imports are not recommended and have a negative impact on performance.
error: Uncaught (in promise) ReferenceError: require is not defined
const external_node_async_hooks_namespaceObject = require("node:async_hooks");
                                                  ^
    at Module.89165 (file:///Users/max_duval/Code/tofu/dotcom-rendering/dist/server.js:17250:51)
    at __webpack_require__ (file:///Users/max_duval/Code/tofu/dotcom-rendering/dist/server.js:52382:42)
    at file:///Users/max_duval/Code/tofu/dotcom-rendering/dist/server.js:52546:37
    at file:///Users/max_duval/Code/tofu/dotcom-rendering/dist/server.js:52549:12
```

This seems to be an issue with [Node’s `AsyncLocalStorage`](https://nodejs.org/docs/latest-v20.x/api/async_context.html#class-asynclocalstorage), which [we use for logging](https://github.com/guardian/dotcom-rendering/blob/38215bff9c81b7cc5dc68433b664ecbb1da24eae/dotcom-rendering/src/server/lib/logging-store.ts#L12).
